    /*
     * Licensed to the Apache Software Foundation (ASF) under one or more
     * contributor license agreements.  See the NOTICE file distributed with
     * this work for additional information regarding copyright ownership.
     * The ASF licenses this file to You under the Apache License, Version 2.0
     * (the "License"); you may not use this file except in compliance with
     * the License.  You may obtain a copy of the License at
     *
     *     http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.airavata.wso2.idp.admin.cpi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class Wso2IdpAdminService {

  public interface Iface {

    public String addTenant(String TenantName) throws org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException, org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void addTenant(String TenantName, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public String addTenant(String TenantName) throws org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException, org.apache.thrift.TException
    {
      send_addTenant(TenantName);
      return recv_addTenant();
    }

    public void send_addTenant(String TenantName) throws org.apache.thrift.TException
    {
      addTenant_args args = new addTenant_args();
      args.setTenantName(TenantName);
      sendBase("addTenant", args);
    }

    public String recv_addTenant() throws org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException, org.apache.thrift.TException
    {
      addTenant_result result = new addTenant_result();
      receiveBase(result, "addTenant");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.wso2IdpAdminServiceException != null) {
        throw result.wso2IdpAdminServiceException;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "addTenant failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void addTenant(String TenantName, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      addTenant_call method_call = new addTenant_call(TenantName, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class addTenant_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String TenantName;
      public addTenant_call(String TenantName, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.TenantName = TenantName;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("addTenant", org.apache.thrift.protocol.TMessageType.CALL, 0));
        addTenant_args args = new addTenant_args();
        args.setTenantName(TenantName);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public String getResult() throws org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_addTenant();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("addTenant", new addTenant());
      return processMap;
    }

    public static class addTenant<I extends Iface> extends org.apache.thrift.ProcessFunction<I, addTenant_args> {
      public addTenant() {
        super("addTenant");
      }

      public addTenant_args getEmptyArgsInstance() {
        return new addTenant_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public addTenant_result getResult(I iface, addTenant_args args) throws org.apache.thrift.TException {
        addTenant_result result = new addTenant_result();
        try {
          result.success = iface.addTenant(args.TenantName);
        } catch (org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException wso2IdpAdminServiceException) {
          result.wso2IdpAdminServiceException = wso2IdpAdminServiceException;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("addTenant", new addTenant());
      return processMap;
    }

    public static class addTenant<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, addTenant_args, String> {
      public addTenant() {
        super("addTenant");
      }

      public addTenant_args getEmptyArgsInstance() {
        return new addTenant_args();
      }

      public AsyncMethodCallback<String> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<String>() { 
          public void onComplete(String o) {
            addTenant_result result = new addTenant_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            addTenant_result result = new addTenant_result();
            if (e instanceof org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException) {
                        result.wso2IdpAdminServiceException = (org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException) e;
                        result.setWso2IdpAdminServiceExceptionIsSet(true);
                        msg = result;
            }
             else 
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, addTenant_args args, org.apache.thrift.async.AsyncMethodCallback<String> resultHandler) throws TException {
        iface.addTenant(args.TenantName,resultHandler);
      }
    }

  }

  public static class addTenant_args implements org.apache.thrift.TBase<addTenant_args, addTenant_args._Fields>, java.io.Serializable, Cloneable, Comparable<addTenant_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("addTenant_args");

    private static final org.apache.thrift.protocol.TField TENANT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("TenantName", org.apache.thrift.protocol.TType.STRING, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new addTenant_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new addTenant_argsTupleSchemeFactory());
    }

    public String TenantName; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      TENANT_NAME((short)1, "TenantName");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // TENANT_NAME
            return TENANT_NAME;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.TENANT_NAME, new org.apache.thrift.meta_data.FieldMetaData("TenantName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(addTenant_args.class, metaDataMap);
    }

    public addTenant_args() {
    }

    public addTenant_args(
      String TenantName)
    {
      this();
      this.TenantName = TenantName;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public addTenant_args(addTenant_args other) {
      if (other.isSetTenantName()) {
        this.TenantName = other.TenantName;
      }
    }

    public addTenant_args deepCopy() {
      return new addTenant_args(this);
    }

    @Override
    public void clear() {
      this.TenantName = null;
    }

    public String getTenantName() {
      return this.TenantName;
    }

    public addTenant_args setTenantName(String TenantName) {
      this.TenantName = TenantName;
      return this;
    }

    public void unsetTenantName() {
      this.TenantName = null;
    }

    /** Returns true if field TenantName is set (has been assigned a value) and false otherwise */
    public boolean isSetTenantName() {
      return this.TenantName != null;
    }

    public void setTenantNameIsSet(boolean value) {
      if (!value) {
        this.TenantName = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case TENANT_NAME:
        if (value == null) {
          unsetTenantName();
        } else {
          setTenantName((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case TENANT_NAME:
        return getTenantName();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case TENANT_NAME:
        return isSetTenantName();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof addTenant_args)
        return this.equals((addTenant_args)that);
      return false;
    }

    public boolean equals(addTenant_args that) {
      if (that == null)
        return false;

      boolean this_present_TenantName = true && this.isSetTenantName();
      boolean that_present_TenantName = true && that.isSetTenantName();
      if (this_present_TenantName || that_present_TenantName) {
        if (!(this_present_TenantName && that_present_TenantName))
          return false;
        if (!this.TenantName.equals(that.TenantName))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_TenantName = true && (isSetTenantName());
      list.add(present_TenantName);
      if (present_TenantName)
        list.add(TenantName);

      return list.hashCode();
    }

    @Override
    public int compareTo(addTenant_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetTenantName()).compareTo(other.isSetTenantName());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetTenantName()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.TenantName, other.TenantName);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("addTenant_args(");
      boolean first = true;

      sb.append("TenantName:");
      if (this.TenantName == null) {
        sb.append("null");
      } else {
        sb.append(this.TenantName);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      if (TenantName == null) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'TenantName' was not present! Struct: " + toString());
      }
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class addTenant_argsStandardSchemeFactory implements SchemeFactory {
      public addTenant_argsStandardScheme getScheme() {
        return new addTenant_argsStandardScheme();
      }
    }

    private static class addTenant_argsStandardScheme extends StandardScheme<addTenant_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, addTenant_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // TENANT_NAME
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.TenantName = iprot.readString();
                struct.setTenantNameIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, addTenant_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.TenantName != null) {
          oprot.writeFieldBegin(TENANT_NAME_FIELD_DESC);
          oprot.writeString(struct.TenantName);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class addTenant_argsTupleSchemeFactory implements SchemeFactory {
      public addTenant_argsTupleScheme getScheme() {
        return new addTenant_argsTupleScheme();
      }
    }

    private static class addTenant_argsTupleScheme extends TupleScheme<addTenant_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, addTenant_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        oprot.writeString(struct.TenantName);
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, addTenant_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        struct.TenantName = iprot.readString();
        struct.setTenantNameIsSet(true);
      }
    }

  }

  public static class addTenant_result implements org.apache.thrift.TBase<addTenant_result, addTenant_result._Fields>, java.io.Serializable, Cloneable, Comparable<addTenant_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("addTenant_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);
    private static final org.apache.thrift.protocol.TField WSO2_IDP_ADMIN_SERVICE_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("wso2IdpAdminServiceException", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new addTenant_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new addTenant_resultTupleSchemeFactory());
    }

    public String success; // required
    public org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException wso2IdpAdminServiceException; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      WSO2_IDP_ADMIN_SERVICE_EXCEPTION((short)1, "wso2IdpAdminServiceException");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // WSO2_IDP_ADMIN_SERVICE_EXCEPTION
            return WSO2_IDP_ADMIN_SERVICE_EXCEPTION;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.WSO2_IDP_ADMIN_SERVICE_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("wso2IdpAdminServiceException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(addTenant_result.class, metaDataMap);
    }

    public addTenant_result() {
    }

    public addTenant_result(
      String success,
      org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException wso2IdpAdminServiceException)
    {
      this();
      this.success = success;
      this.wso2IdpAdminServiceException = wso2IdpAdminServiceException;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public addTenant_result(addTenant_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
      if (other.isSetWso2IdpAdminServiceException()) {
        this.wso2IdpAdminServiceException = new org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException(other.wso2IdpAdminServiceException);
      }
    }

    public addTenant_result deepCopy() {
      return new addTenant_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.wso2IdpAdminServiceException = null;
    }

    public String getSuccess() {
      return this.success;
    }

    public addTenant_result setSuccess(String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException getWso2IdpAdminServiceException() {
      return this.wso2IdpAdminServiceException;
    }

    public addTenant_result setWso2IdpAdminServiceException(org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException wso2IdpAdminServiceException) {
      this.wso2IdpAdminServiceException = wso2IdpAdminServiceException;
      return this;
    }

    public void unsetWso2IdpAdminServiceException() {
      this.wso2IdpAdminServiceException = null;
    }

    /** Returns true if field wso2IdpAdminServiceException is set (has been assigned a value) and false otherwise */
    public boolean isSetWso2IdpAdminServiceException() {
      return this.wso2IdpAdminServiceException != null;
    }

    public void setWso2IdpAdminServiceExceptionIsSet(boolean value) {
      if (!value) {
        this.wso2IdpAdminServiceException = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((String)value);
        }
        break;

      case WSO2_IDP_ADMIN_SERVICE_EXCEPTION:
        if (value == null) {
          unsetWso2IdpAdminServiceException();
        } else {
          setWso2IdpAdminServiceException((org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case WSO2_IDP_ADMIN_SERVICE_EXCEPTION:
        return getWso2IdpAdminServiceException();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case WSO2_IDP_ADMIN_SERVICE_EXCEPTION:
        return isSetWso2IdpAdminServiceException();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof addTenant_result)
        return this.equals((addTenant_result)that);
      return false;
    }

    public boolean equals(addTenant_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_wso2IdpAdminServiceException = true && this.isSetWso2IdpAdminServiceException();
      boolean that_present_wso2IdpAdminServiceException = true && that.isSetWso2IdpAdminServiceException();
      if (this_present_wso2IdpAdminServiceException || that_present_wso2IdpAdminServiceException) {
        if (!(this_present_wso2IdpAdminServiceException && that_present_wso2IdpAdminServiceException))
          return false;
        if (!this.wso2IdpAdminServiceException.equals(that.wso2IdpAdminServiceException))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      boolean present_wso2IdpAdminServiceException = true && (isSetWso2IdpAdminServiceException());
      list.add(present_wso2IdpAdminServiceException);
      if (present_wso2IdpAdminServiceException)
        list.add(wso2IdpAdminServiceException);

      return list.hashCode();
    }

    @Override
    public int compareTo(addTenant_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetWso2IdpAdminServiceException()).compareTo(other.isSetWso2IdpAdminServiceException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetWso2IdpAdminServiceException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.wso2IdpAdminServiceException, other.wso2IdpAdminServiceException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("addTenant_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("wso2IdpAdminServiceException:");
      if (this.wso2IdpAdminServiceException == null) {
        sb.append("null");
      } else {
        sb.append(this.wso2IdpAdminServiceException);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class addTenant_resultStandardSchemeFactory implements SchemeFactory {
      public addTenant_resultStandardScheme getScheme() {
        return new addTenant_resultStandardScheme();
      }
    }

    private static class addTenant_resultStandardScheme extends StandardScheme<addTenant_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, addTenant_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // WSO2_IDP_ADMIN_SERVICE_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.wso2IdpAdminServiceException = new org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException();
                struct.wso2IdpAdminServiceException.read(iprot);
                struct.setWso2IdpAdminServiceExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, addTenant_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        if (struct.wso2IdpAdminServiceException != null) {
          oprot.writeFieldBegin(WSO2_IDP_ADMIN_SERVICE_EXCEPTION_FIELD_DESC);
          struct.wso2IdpAdminServiceException.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class addTenant_resultTupleSchemeFactory implements SchemeFactory {
      public addTenant_resultTupleScheme getScheme() {
        return new addTenant_resultTupleScheme();
      }
    }

    private static class addTenant_resultTupleScheme extends TupleScheme<addTenant_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, addTenant_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetWso2IdpAdminServiceException()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
        if (struct.isSetWso2IdpAdminServiceException()) {
          struct.wso2IdpAdminServiceException.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, addTenant_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.wso2IdpAdminServiceException = new org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException();
          struct.wso2IdpAdminServiceException.read(iprot);
          struct.setWso2IdpAdminServiceExceptionIsSet(true);
        }
      }
    }

  }

}
