    /*
     * Licensed to the Apache Software Foundation (ASF) under one or more
     * contributor license agreements.  See the NOTICE file distributed with
     * this work for additional information regarding copyright ownership.
     * The ASF licenses this file to You under the Apache License, Version 2.0
     * (the "License"); you may not use this file except in compliance with
     * the License.  You may obtain a copy of the License at
     *
     *     http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.airavata.wso2.idp.admin.cpi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class Wso2IdpAdminService {

  public interface Iface {

    public boolean addTenant(org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean, String superAdminPWDCredentialAccessToken, String adminGatewayID) throws org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException, org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void addTenant(org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean, String superAdminPWDCredentialAccessToken, String adminGatewayID, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public boolean addTenant(org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean, String superAdminPWDCredentialAccessToken, String adminGatewayID) throws org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException, org.apache.thrift.TException
    {
      send_addTenant(tenantInfoBean, superAdminPWDCredentialAccessToken, adminGatewayID);
      return recv_addTenant();
    }

    public void send_addTenant(org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean, String superAdminPWDCredentialAccessToken, String adminGatewayID) throws org.apache.thrift.TException
    {
      addTenant_args args = new addTenant_args();
      args.setTenantInfoBean(tenantInfoBean);
      args.setSuperAdminPWDCredentialAccessToken(superAdminPWDCredentialAccessToken);
      args.setAdminGatewayID(adminGatewayID);
      sendBase("addTenant", args);
    }

    public boolean recv_addTenant() throws org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException, org.apache.thrift.TException
    {
      addTenant_result result = new addTenant_result();
      receiveBase(result, "addTenant");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.wso2IdpAdminServiceException != null) {
        throw result.wso2IdpAdminServiceException;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "addTenant failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void addTenant(org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean, String superAdminPWDCredentialAccessToken, String adminGatewayID, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      addTenant_call method_call = new addTenant_call(tenantInfoBean, superAdminPWDCredentialAccessToken, adminGatewayID, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class addTenant_call extends org.apache.thrift.async.TAsyncMethodCall {
      private org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean;
      private String superAdminPWDCredentialAccessToken;
      private String adminGatewayID;
      public addTenant_call(org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean, String superAdminPWDCredentialAccessToken, String adminGatewayID, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.tenantInfoBean = tenantInfoBean;
        this.superAdminPWDCredentialAccessToken = superAdminPWDCredentialAccessToken;
        this.adminGatewayID = adminGatewayID;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("addTenant", org.apache.thrift.protocol.TMessageType.CALL, 0));
        addTenant_args args = new addTenant_args();
        args.setTenantInfoBean(tenantInfoBean);
        args.setSuperAdminPWDCredentialAccessToken(superAdminPWDCredentialAccessToken);
        args.setAdminGatewayID(adminGatewayID);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public boolean getResult() throws org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_addTenant();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("addTenant", new addTenant());
      return processMap;
    }

    public static class addTenant<I extends Iface> extends org.apache.thrift.ProcessFunction<I, addTenant_args> {
      public addTenant() {
        super("addTenant");
      }

      public addTenant_args getEmptyArgsInstance() {
        return new addTenant_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public addTenant_result getResult(I iface, addTenant_args args) throws org.apache.thrift.TException {
        addTenant_result result = new addTenant_result();
        try {
          result.success = iface.addTenant(args.tenantInfoBean, args.superAdminPWDCredentialAccessToken, args.adminGatewayID);
          result.setSuccessIsSet(true);
        } catch (org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException wso2IdpAdminServiceException) {
          result.wso2IdpAdminServiceException = wso2IdpAdminServiceException;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("addTenant", new addTenant());
      return processMap;
    }

    public static class addTenant<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, addTenant_args, Boolean> {
      public addTenant() {
        super("addTenant");
      }

      public addTenant_args getEmptyArgsInstance() {
        return new addTenant_args();
      }

      public AsyncMethodCallback<Boolean> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<Boolean>() { 
          public void onComplete(Boolean o) {
            addTenant_result result = new addTenant_result();
            result.success = o;
            result.setSuccessIsSet(true);
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            addTenant_result result = new addTenant_result();
            if (e instanceof org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException) {
                        result.wso2IdpAdminServiceException = (org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException) e;
                        result.setWso2IdpAdminServiceExceptionIsSet(true);
                        msg = result;
            }
             else 
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, addTenant_args args, org.apache.thrift.async.AsyncMethodCallback<Boolean> resultHandler) throws TException {
        iface.addTenant(args.tenantInfoBean, args.superAdminPWDCredentialAccessToken, args.adminGatewayID,resultHandler);
      }
    }

  }

  public static class addTenant_args implements org.apache.thrift.TBase<addTenant_args, addTenant_args._Fields>, java.io.Serializable, Cloneable, Comparable<addTenant_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("addTenant_args");

    private static final org.apache.thrift.protocol.TField TENANT_INFO_BEAN_FIELD_DESC = new org.apache.thrift.protocol.TField("tenantInfoBean", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("superAdminPWDCredentialAccessToken", org.apache.thrift.protocol.TType.STRING, (short)2);
    private static final org.apache.thrift.protocol.TField ADMIN_GATEWAY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("adminGatewayID", org.apache.thrift.protocol.TType.STRING, (short)3);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new addTenant_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new addTenant_argsTupleSchemeFactory());
    }

    public org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean; // required
    public String superAdminPWDCredentialAccessToken; // required
    public String adminGatewayID; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      TENANT_INFO_BEAN((short)1, "tenantInfoBean"),
      SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN((short)2, "superAdminPWDCredentialAccessToken"),
      ADMIN_GATEWAY_ID((short)3, "adminGatewayID");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // TENANT_INFO_BEAN
            return TENANT_INFO_BEAN;
          case 2: // SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN
            return SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN;
          case 3: // ADMIN_GATEWAY_ID
            return ADMIN_GATEWAY_ID;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.TENANT_INFO_BEAN, new org.apache.thrift.meta_data.FieldMetaData("tenantInfoBean", org.apache.thrift.TFieldRequirementType.REQUIRED, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, org.apache.airavata.model.wso2.adminservice.TenantInfoBean.class)));
      tmpMap.put(_Fields.SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN, new org.apache.thrift.meta_data.FieldMetaData("superAdminPWDCredentialAccessToken", org.apache.thrift.TFieldRequirementType.REQUIRED, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.ADMIN_GATEWAY_ID, new org.apache.thrift.meta_data.FieldMetaData("adminGatewayID", org.apache.thrift.TFieldRequirementType.REQUIRED, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(addTenant_args.class, metaDataMap);
    }

    public addTenant_args() {
    }

    public addTenant_args(
      org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean,
      String superAdminPWDCredentialAccessToken,
      String adminGatewayID)
    {
      this();
      this.tenantInfoBean = tenantInfoBean;
      this.superAdminPWDCredentialAccessToken = superAdminPWDCredentialAccessToken;
      this.adminGatewayID = adminGatewayID;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public addTenant_args(addTenant_args other) {
      if (other.isSetTenantInfoBean()) {
        this.tenantInfoBean = new org.apache.airavata.model.wso2.adminservice.TenantInfoBean(other.tenantInfoBean);
      }
      if (other.isSetSuperAdminPWDCredentialAccessToken()) {
        this.superAdminPWDCredentialAccessToken = other.superAdminPWDCredentialAccessToken;
      }
      if (other.isSetAdminGatewayID()) {
        this.adminGatewayID = other.adminGatewayID;
      }
    }

    public addTenant_args deepCopy() {
      return new addTenant_args(this);
    }

    @Override
    public void clear() {
      this.tenantInfoBean = null;
      this.superAdminPWDCredentialAccessToken = null;
      this.adminGatewayID = null;
    }

    public org.apache.airavata.model.wso2.adminservice.TenantInfoBean getTenantInfoBean() {
      return this.tenantInfoBean;
    }

    public addTenant_args setTenantInfoBean(org.apache.airavata.model.wso2.adminservice.TenantInfoBean tenantInfoBean) {
      this.tenantInfoBean = tenantInfoBean;
      return this;
    }

    public void unsetTenantInfoBean() {
      this.tenantInfoBean = null;
    }

    /** Returns true if field tenantInfoBean is set (has been assigned a value) and false otherwise */
    public boolean isSetTenantInfoBean() {
      return this.tenantInfoBean != null;
    }

    public void setTenantInfoBeanIsSet(boolean value) {
      if (!value) {
        this.tenantInfoBean = null;
      }
    }

    public String getSuperAdminPWDCredentialAccessToken() {
      return this.superAdminPWDCredentialAccessToken;
    }

    public addTenant_args setSuperAdminPWDCredentialAccessToken(String superAdminPWDCredentialAccessToken) {
      this.superAdminPWDCredentialAccessToken = superAdminPWDCredentialAccessToken;
      return this;
    }

    public void unsetSuperAdminPWDCredentialAccessToken() {
      this.superAdminPWDCredentialAccessToken = null;
    }

    /** Returns true if field superAdminPWDCredentialAccessToken is set (has been assigned a value) and false otherwise */
    public boolean isSetSuperAdminPWDCredentialAccessToken() {
      return this.superAdminPWDCredentialAccessToken != null;
    }

    public void setSuperAdminPWDCredentialAccessTokenIsSet(boolean value) {
      if (!value) {
        this.superAdminPWDCredentialAccessToken = null;
      }
    }

    public String getAdminGatewayID() {
      return this.adminGatewayID;
    }

    public addTenant_args setAdminGatewayID(String adminGatewayID) {
      this.adminGatewayID = adminGatewayID;
      return this;
    }

    public void unsetAdminGatewayID() {
      this.adminGatewayID = null;
    }

    /** Returns true if field adminGatewayID is set (has been assigned a value) and false otherwise */
    public boolean isSetAdminGatewayID() {
      return this.adminGatewayID != null;
    }

    public void setAdminGatewayIDIsSet(boolean value) {
      if (!value) {
        this.adminGatewayID = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case TENANT_INFO_BEAN:
        if (value == null) {
          unsetTenantInfoBean();
        } else {
          setTenantInfoBean((org.apache.airavata.model.wso2.adminservice.TenantInfoBean)value);
        }
        break;

      case SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN:
        if (value == null) {
          unsetSuperAdminPWDCredentialAccessToken();
        } else {
          setSuperAdminPWDCredentialAccessToken((String)value);
        }
        break;

      case ADMIN_GATEWAY_ID:
        if (value == null) {
          unsetAdminGatewayID();
        } else {
          setAdminGatewayID((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case TENANT_INFO_BEAN:
        return getTenantInfoBean();

      case SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN:
        return getSuperAdminPWDCredentialAccessToken();

      case ADMIN_GATEWAY_ID:
        return getAdminGatewayID();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case TENANT_INFO_BEAN:
        return isSetTenantInfoBean();
      case SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN:
        return isSetSuperAdminPWDCredentialAccessToken();
      case ADMIN_GATEWAY_ID:
        return isSetAdminGatewayID();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof addTenant_args)
        return this.equals((addTenant_args)that);
      return false;
    }

    public boolean equals(addTenant_args that) {
      if (that == null)
        return false;

      boolean this_present_tenantInfoBean = true && this.isSetTenantInfoBean();
      boolean that_present_tenantInfoBean = true && that.isSetTenantInfoBean();
      if (this_present_tenantInfoBean || that_present_tenantInfoBean) {
        if (!(this_present_tenantInfoBean && that_present_tenantInfoBean))
          return false;
        if (!this.tenantInfoBean.equals(that.tenantInfoBean))
          return false;
      }

      boolean this_present_superAdminPWDCredentialAccessToken = true && this.isSetSuperAdminPWDCredentialAccessToken();
      boolean that_present_superAdminPWDCredentialAccessToken = true && that.isSetSuperAdminPWDCredentialAccessToken();
      if (this_present_superAdminPWDCredentialAccessToken || that_present_superAdminPWDCredentialAccessToken) {
        if (!(this_present_superAdminPWDCredentialAccessToken && that_present_superAdminPWDCredentialAccessToken))
          return false;
        if (!this.superAdminPWDCredentialAccessToken.equals(that.superAdminPWDCredentialAccessToken))
          return false;
      }

      boolean this_present_adminGatewayID = true && this.isSetAdminGatewayID();
      boolean that_present_adminGatewayID = true && that.isSetAdminGatewayID();
      if (this_present_adminGatewayID || that_present_adminGatewayID) {
        if (!(this_present_adminGatewayID && that_present_adminGatewayID))
          return false;
        if (!this.adminGatewayID.equals(that.adminGatewayID))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_tenantInfoBean = true && (isSetTenantInfoBean());
      list.add(present_tenantInfoBean);
      if (present_tenantInfoBean)
        list.add(tenantInfoBean);

      boolean present_superAdminPWDCredentialAccessToken = true && (isSetSuperAdminPWDCredentialAccessToken());
      list.add(present_superAdminPWDCredentialAccessToken);
      if (present_superAdminPWDCredentialAccessToken)
        list.add(superAdminPWDCredentialAccessToken);

      boolean present_adminGatewayID = true && (isSetAdminGatewayID());
      list.add(present_adminGatewayID);
      if (present_adminGatewayID)
        list.add(adminGatewayID);

      return list.hashCode();
    }

    @Override
    public int compareTo(addTenant_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetTenantInfoBean()).compareTo(other.isSetTenantInfoBean());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetTenantInfoBean()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tenantInfoBean, other.tenantInfoBean);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetSuperAdminPWDCredentialAccessToken()).compareTo(other.isSetSuperAdminPWDCredentialAccessToken());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuperAdminPWDCredentialAccessToken()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.superAdminPWDCredentialAccessToken, other.superAdminPWDCredentialAccessToken);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAdminGatewayID()).compareTo(other.isSetAdminGatewayID());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAdminGatewayID()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adminGatewayID, other.adminGatewayID);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("addTenant_args(");
      boolean first = true;

      sb.append("tenantInfoBean:");
      if (this.tenantInfoBean == null) {
        sb.append("null");
      } else {
        sb.append(this.tenantInfoBean);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("superAdminPWDCredentialAccessToken:");
      if (this.superAdminPWDCredentialAccessToken == null) {
        sb.append("null");
      } else {
        sb.append(this.superAdminPWDCredentialAccessToken);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("adminGatewayID:");
      if (this.adminGatewayID == null) {
        sb.append("null");
      } else {
        sb.append(this.adminGatewayID);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      if (tenantInfoBean == null) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'tenantInfoBean' was not present! Struct: " + toString());
      }
      if (superAdminPWDCredentialAccessToken == null) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'superAdminPWDCredentialAccessToken' was not present! Struct: " + toString());
      }
      if (adminGatewayID == null) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'adminGatewayID' was not present! Struct: " + toString());
      }
      // check for sub-struct validity
      if (tenantInfoBean != null) {
        tenantInfoBean.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class addTenant_argsStandardSchemeFactory implements SchemeFactory {
      public addTenant_argsStandardScheme getScheme() {
        return new addTenant_argsStandardScheme();
      }
    }

    private static class addTenant_argsStandardScheme extends StandardScheme<addTenant_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, addTenant_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // TENANT_INFO_BEAN
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.tenantInfoBean = new org.apache.airavata.model.wso2.adminservice.TenantInfoBean();
                struct.tenantInfoBean.read(iprot);
                struct.setTenantInfoBeanIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.superAdminPWDCredentialAccessToken = iprot.readString();
                struct.setSuperAdminPWDCredentialAccessTokenIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // ADMIN_GATEWAY_ID
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.adminGatewayID = iprot.readString();
                struct.setAdminGatewayIDIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, addTenant_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.tenantInfoBean != null) {
          oprot.writeFieldBegin(TENANT_INFO_BEAN_FIELD_DESC);
          struct.tenantInfoBean.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.superAdminPWDCredentialAccessToken != null) {
          oprot.writeFieldBegin(SUPER_ADMIN_PWDCREDENTIAL_ACCESS_TOKEN_FIELD_DESC);
          oprot.writeString(struct.superAdminPWDCredentialAccessToken);
          oprot.writeFieldEnd();
        }
        if (struct.adminGatewayID != null) {
          oprot.writeFieldBegin(ADMIN_GATEWAY_ID_FIELD_DESC);
          oprot.writeString(struct.adminGatewayID);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class addTenant_argsTupleSchemeFactory implements SchemeFactory {
      public addTenant_argsTupleScheme getScheme() {
        return new addTenant_argsTupleScheme();
      }
    }

    private static class addTenant_argsTupleScheme extends TupleScheme<addTenant_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, addTenant_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        struct.tenantInfoBean.write(oprot);
        oprot.writeString(struct.superAdminPWDCredentialAccessToken);
        oprot.writeString(struct.adminGatewayID);
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, addTenant_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        struct.tenantInfoBean = new org.apache.airavata.model.wso2.adminservice.TenantInfoBean();
        struct.tenantInfoBean.read(iprot);
        struct.setTenantInfoBeanIsSet(true);
        struct.superAdminPWDCredentialAccessToken = iprot.readString();
        struct.setSuperAdminPWDCredentialAccessTokenIsSet(true);
        struct.adminGatewayID = iprot.readString();
        struct.setAdminGatewayIDIsSet(true);
      }
    }

  }

  public static class addTenant_result implements org.apache.thrift.TBase<addTenant_result, addTenant_result._Fields>, java.io.Serializable, Cloneable, Comparable<addTenant_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("addTenant_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.BOOL, (short)0);
    private static final org.apache.thrift.protocol.TField WSO2_IDP_ADMIN_SERVICE_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("wso2IdpAdminServiceException", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new addTenant_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new addTenant_resultTupleSchemeFactory());
    }

    public boolean success; // required
    public org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException wso2IdpAdminServiceException; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      WSO2_IDP_ADMIN_SERVICE_EXCEPTION((short)1, "wso2IdpAdminServiceException");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // WSO2_IDP_ADMIN_SERVICE_EXCEPTION
            return WSO2_IDP_ADMIN_SERVICE_EXCEPTION;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __SUCCESS_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
      tmpMap.put(_Fields.WSO2_IDP_ADMIN_SERVICE_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("wso2IdpAdminServiceException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(addTenant_result.class, metaDataMap);
    }

    public addTenant_result() {
    }

    public addTenant_result(
      boolean success,
      org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException wso2IdpAdminServiceException)
    {
      this();
      this.success = success;
      setSuccessIsSet(true);
      this.wso2IdpAdminServiceException = wso2IdpAdminServiceException;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public addTenant_result(addTenant_result other) {
      __isset_bitfield = other.__isset_bitfield;
      this.success = other.success;
      if (other.isSetWso2IdpAdminServiceException()) {
        this.wso2IdpAdminServiceException = new org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException(other.wso2IdpAdminServiceException);
      }
    }

    public addTenant_result deepCopy() {
      return new addTenant_result(this);
    }

    @Override
    public void clear() {
      setSuccessIsSet(false);
      this.success = false;
      this.wso2IdpAdminServiceException = null;
    }

    public boolean isSuccess() {
      return this.success;
    }

    public addTenant_result setSuccess(boolean success) {
      this.success = success;
      setSuccessIsSet(true);
      return this;
    }

    public void unsetSuccess() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    public void setSuccessIsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
    }

    public org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException getWso2IdpAdminServiceException() {
      return this.wso2IdpAdminServiceException;
    }

    public addTenant_result setWso2IdpAdminServiceException(org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException wso2IdpAdminServiceException) {
      this.wso2IdpAdminServiceException = wso2IdpAdminServiceException;
      return this;
    }

    public void unsetWso2IdpAdminServiceException() {
      this.wso2IdpAdminServiceException = null;
    }

    /** Returns true if field wso2IdpAdminServiceException is set (has been assigned a value) and false otherwise */
    public boolean isSetWso2IdpAdminServiceException() {
      return this.wso2IdpAdminServiceException != null;
    }

    public void setWso2IdpAdminServiceExceptionIsSet(boolean value) {
      if (!value) {
        this.wso2IdpAdminServiceException = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Boolean)value);
        }
        break;

      case WSO2_IDP_ADMIN_SERVICE_EXCEPTION:
        if (value == null) {
          unsetWso2IdpAdminServiceException();
        } else {
          setWso2IdpAdminServiceException((org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return isSuccess();

      case WSO2_IDP_ADMIN_SERVICE_EXCEPTION:
        return getWso2IdpAdminServiceException();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case WSO2_IDP_ADMIN_SERVICE_EXCEPTION:
        return isSetWso2IdpAdminServiceException();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof addTenant_result)
        return this.equals((addTenant_result)that);
      return false;
    }

    public boolean equals(addTenant_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true;
      boolean that_present_success = true;
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (this.success != that.success)
          return false;
      }

      boolean this_present_wso2IdpAdminServiceException = true && this.isSetWso2IdpAdminServiceException();
      boolean that_present_wso2IdpAdminServiceException = true && that.isSetWso2IdpAdminServiceException();
      if (this_present_wso2IdpAdminServiceException || that_present_wso2IdpAdminServiceException) {
        if (!(this_present_wso2IdpAdminServiceException && that_present_wso2IdpAdminServiceException))
          return false;
        if (!this.wso2IdpAdminServiceException.equals(that.wso2IdpAdminServiceException))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true;
      list.add(present_success);
      if (present_success)
        list.add(success);

      boolean present_wso2IdpAdminServiceException = true && (isSetWso2IdpAdminServiceException());
      list.add(present_wso2IdpAdminServiceException);
      if (present_wso2IdpAdminServiceException)
        list.add(wso2IdpAdminServiceException);

      return list.hashCode();
    }

    @Override
    public int compareTo(addTenant_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetWso2IdpAdminServiceException()).compareTo(other.isSetWso2IdpAdminServiceException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetWso2IdpAdminServiceException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.wso2IdpAdminServiceException, other.wso2IdpAdminServiceException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("addTenant_result(");
      boolean first = true;

      sb.append("success:");
      sb.append(this.success);
      first = false;
      if (!first) sb.append(", ");
      sb.append("wso2IdpAdminServiceException:");
      if (this.wso2IdpAdminServiceException == null) {
        sb.append("null");
      } else {
        sb.append(this.wso2IdpAdminServiceException);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class addTenant_resultStandardSchemeFactory implements SchemeFactory {
      public addTenant_resultStandardScheme getScheme() {
        return new addTenant_resultStandardScheme();
      }
    }

    private static class addTenant_resultStandardScheme extends StandardScheme<addTenant_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, addTenant_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                struct.success = iprot.readBool();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // WSO2_IDP_ADMIN_SERVICE_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.wso2IdpAdminServiceException = new org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException();
                struct.wso2IdpAdminServiceException.read(iprot);
                struct.setWso2IdpAdminServiceExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, addTenant_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.isSetSuccess()) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeBool(struct.success);
          oprot.writeFieldEnd();
        }
        if (struct.wso2IdpAdminServiceException != null) {
          oprot.writeFieldBegin(WSO2_IDP_ADMIN_SERVICE_EXCEPTION_FIELD_DESC);
          struct.wso2IdpAdminServiceException.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class addTenant_resultTupleSchemeFactory implements SchemeFactory {
      public addTenant_resultTupleScheme getScheme() {
        return new addTenant_resultTupleScheme();
      }
    }

    private static class addTenant_resultTupleScheme extends TupleScheme<addTenant_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, addTenant_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetWso2IdpAdminServiceException()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetSuccess()) {
          oprot.writeBool(struct.success);
        }
        if (struct.isSetWso2IdpAdminServiceException()) {
          struct.wso2IdpAdminServiceException.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, addTenant_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.success = iprot.readBool();
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.wso2IdpAdminServiceException = new org.apache.airavata.wso2.idp.admin.cpi.exceptions.Wso2IdpAdminServiceException();
          struct.wso2IdpAdminServiceException.read(iprot);
          struct.setWso2IdpAdminServiceExceptionIsSet(true);
        }
      }
    }

  }

}
